config_path: "/home/isaacp/repos/RLEVMatsim/contribs/rlEvWireless/scenario_examples/tinytown_scenario_example/ev_tiny_town_config.xml"
# How many agents to use to run optimal charger placement (OCP) per environment
num_agents_per_env: 1
results_dir: "./utah_ev_ocp_results"
charge_model_path: "/home/isaacp/repos/RLEVMatsim/contribs/rlEvWireless/results/ocp/ocp/happo/marl_ocp/seed-00001-2025-05-21-15-24-48/matsim_charge_model.pt"
# How often to update the model with the actual charge efficiency retrieved from the server, every (charge_model_loop / (episode_length)) episodes
charge_model_loop: 1000
# When updating the charge model on the server output, how many iterations to train for
charge_model_iters: 10
# How many iterations to finetune the model before the OCP RL loop begins
charge_model_pretraining_epochs:
learning_rate: 0.001
server_port: 8000
num_server_threads: 2
# How often to save the server output, keep in mind this will run the simulation on the server
# every save_server_output_interval steps which can slow down training
save_server_output_interval: 1000
