config_path: "/home/isaacp/repos/RLEVMatsim/contribs/rlEvWireless/scenario_examples/tinytown_scenario_example/ev_tiny_town_config.xml"
# How many agents to use to run optimal charger placement (OCP) per environment
num_agents_per_env: 1
results_dir: "./utah_ev_ocp_results"
charge_model_path: "/home/isaacp/repos/RLEVMatsim/contribs/rlEvWireless/results/ocp/ocp/happo/marl_ocp/trained_mlp/matsim_charge_model.pt"
# How often to update the model with the actual charge efficiency retrieved from the server, every (charge_model_loop / (episode_length)) episodes
charge_model_loop: 1000
# When updating the charge model on the server output, how many iterations to train for
charge_model_iters: 1
# How many iterations to finetune the model before the OCP RL loop begins
charge_model_pretraining_epochs:
learning_rate: 0.001
server_port: 8000
# model_type can be gnn or mlp
model_type: "mlp"
