config_path: "/home/isaacp/repos/RLEVMatsim/contribs/rlEvWireless/scenario_examples/tinytown_scenario_example/ev_tiny_town_config.xml"
num_agents_per_env: 10
results_dir: "./utah_ev_ocp_results"
charge_model_path:
charge_model_loop: 100
charge_model_pretraining_epochs: 25
learning_rate: 1e-3
